# -*- coding:utf-8 -*-
import pytest
import time
import allure

from utils import Utils, ssh_clinet

ssh = ssh_clinet.SSHClient()


def setup_module():
    ssh.connnect()
    ssh.executor('export HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S $ "')
    ssh.executor('cd /mnt/lustre/share/gmllog && mkdir pytest_log_05202224 && cd ~ && rm -rf gml_daily/GML_data/')
    ssh.executor('tmux kill-server')
    ssh.executor("""rm -rf .local.pt* &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step1.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""source pt1.6.0 mmcv=1.4.6 &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step2.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""cd ~/gml_daily && rm -rf gml &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step3.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""git clone git@gitlab.sz.sensetime.com:parrotsDL-sz/gml.git &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step4.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""cd ~/gml_daily/gml && mkdir -p data && cd ~/gml_daily/gml/data &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step5.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""cp -r ~/ly/data ~/gml_daily/gml/demo/ && cd ~/gml_daily/gml/demo/data/MNIST/raw &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step6.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""find . -name "*.gz" | xargs gunzip &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step7.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""cd ~/gml_daily/gml && mkdir .dev && cd .dev &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step8.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""git clone git@gitlab.sz.sensetime.com:parrotsDL-sz/mmclassification.git &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step9.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""cd  ~/gml_daily/gml/.dev/mmclassification && export PYTHONPATH=`pwd`:$PYTHONPATH &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step10.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""git checkout master-opensource &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step11.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""pip install -e . --user &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step12.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""cd ~/gml_daily/gml/.dev &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step13.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""git clone git@gitlab.sz.sensetime.com:parrotsDL-sz/mmdetection.git &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step14.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""cd ~/gml_daily/gml/.dev/mmdetection && export PYTHONPATH=`pwd`:$PYTHONPATH &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step15.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""git checkout master-opensource &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step16.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""pip install -e . --user &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step17.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""sed -i "s/train2017/val2017/g" ~/gml_daily/gml/configs/_base_/datasets/mmdet/coco_detection.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step18.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""sed -i "s/pat_prototype/pat_dev/g" ~/gml_daily/gml/configs/hpo/gridsearch/search_config.yaml &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step19.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""sed -i "s/20/2/g" ~/gml_daily/gml/configs/hpo/gridsearch/search_config.yaml &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step20.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""pip install --index-url https://pkg.sensetime.com/repository/pypi-proxy/simple/ --extra-index-url http://pavi.parrots.sensetime.com/pypi/simple/ --trusted-host pavi.parrots.sensetime.com -U --user pavi &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step21.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    time.sleep(300)
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""pavi logout -f && pavi login -t 1 -u platform.tester.s.01 -p sense@1234 &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step23.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""cd ~/gml_daily/gml/configs &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step24.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""python get_data_from_modelhub.py modelhub_model_list.txt ../../ &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step25.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""cd ~/gml_daily/gml/data && ln -s ../../GML_data/gml_unique ./ && ln -s ../../GML_data/gml_checkpoint/ ./ &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step26.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""cd ~/gml_daily/gml && export PYTHONPATH=`pwd`:$PYTHONPATH &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step27.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""pip install -e . --user &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step28.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""pip install -r requirements.txt --user &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step29.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""cd ~/gml_daily/gml/demo &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step30.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""python process.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step31.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""search-init &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step32.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""sed -i "s#ann_file='data/imagenet#ann_file='data/gml_unique/imagenet-1k#g" ~/gml_daily/gml/configs/_base_/datasets/mmcls/imagenet_bs64_pil_resize_autoaugv2.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step33.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""sed -i "s#ann_file='data/imagenet#ann_file='data/gml_unique/imagenet-1k#g" ~/gml_daily/gml/configs/_base_/datasets/mmcls/imagenet_bs64_pil_resize_autoaugv1.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step34.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""sed -i "s#ann_file='data/imagenet#ann_file='data/gml_unique/imagenet-1k#g" ~/gml_daily/gml/configs/_base_/datasets/mmcls/imagenet_bs128_colorjittor.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step35.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""sed -i "s#ann_file='data/imagenet#ann_file='data/gml_unique/imagenet-1k#g" ~/gml_daily/gml/configs/_base_/datasets/mmcls/imagenet_bs64_autoformer_224.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step36.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""sed -i "s#ann_file='data/imagenet#ann_file='data/gml_unique/imagenet-1k#g" ~/gml_daily/gml/configs/_base_/datasets/mmcls/imagenet_bs128_cream_224.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step37.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""sed -i "s#ann_file=data_root + '#ann_file='data/gml_unique/coco/#g" ~/gml_daily/gml/configs/_base_/datasets/mmdet/detnas_coco_detection.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step38.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""sed -i "s#data_prefix='data/imagenet/#data_prefix='s3://PAT/datasets/project_data/gml_data/gml_unique/imagenet_1k/#g" ~/gml_daily/gml/configs/_base_/datasets/mmcls/imagenet_bs64_pil_resize_autoaugv1.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step39.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""sed -i "s#data_prefix='data/imagenet/#data_prefix='s3://PAT/datasets/project_data/gml_data/gml_unique/imagenet_1k/#g" ~/gml_daily/gml/configs/_base_/datasets/mmcls/imagenet_bs128_colorjittor.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step40.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""sed -i "s#data_prefix='data/imagenet/#data_prefix='s3://PAT/datasets/project_data/gml_data/gml_unique/imagenet_1k/#g" ~/gml_daily/gml/configs/_base_/datasets/mmcls/imagenet_bs64_autoformer_224.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step41.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""sed -i "s#data_prefix='data/imagenet/#data_prefix='s3://PAT/datasets/project_data/gml_data/gml_unique/imagenet_1k/#g" ~/gml_daily/gml/configs/_base_/datasets/mmcls/imagenet_bs128_cream_224.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step42.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""sed -i "s#data_prefix='data/imagenet/#data_prefix='s3://PAT/datasets/project_data/gml_data/gml_unique/imagenet_1k/#g" ~/gml_daily/gml/configs/_base_/datasets/mmcls/imagenet_bs64_pil_resize_autoaugv2.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step43.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
    ssh.executor("""ln -sf /mnt/lustre/share_data/huangpengsheng/gml_data/cifar10* ~/gml_daily/gml/data &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_module_step44.txt""")
    print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))


class Testhpo:

    def setup_class(self):
        ssh.executor('cd ~/gml_daily/gml')
        ssh.executor("""cd ~/gml_daily/gml/demo &> /mnt/lustre/share/gmllog/pytest_log_05202224/setup_class_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))

    @pytest.mark.run(order=1)
    @allure.title('hpo_gridsearch_search_run_t_task')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_run_t_task_step1.txt')
    def test_hpo_gridsearch_search_run_t_task(self):
        ssh.executor("""search-run -t hpo_gridsearch_search_run_t_task05202224 ../configs/hpo/gridsearch/search_config.yaml &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_run_t_task_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'Task hpo_gridsearch_search_run_t_task05202224 finished', '/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_run_t_task')

    @pytest.mark.run(order=2)
    @allure.title('hpo_gridsearch_search_stop')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_stop_step3.txt')
    def test_hpo_gridsearch_search_stop(self):
        ssh.executor("""tmux new -s hpo_gridsearch_search_stop""", max_wait=3)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""tmux detach""", max_wait=3)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""tmux send-keys -t hpo_gridsearch_search_stop 'source pt1.6.0 mmcv=1.4.6' C-m""", max_wait=3)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""tmux send-keys -t hpo_gridsearch_search_stop 'cd ~/gml_daily/gml/demo' C-m""", max_wait=3)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""tmux send-keys -t hpo_gridsearch_search_stop 'search-run -t hpo_gridsearch_search_stop05202224 ../configs/hpo/gridsearch/search_config.yaml' C-m""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(180)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""search-ctl stop -t hpo_gridsearch_search_stop05202224 &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_stop_step3.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'Kill', '/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_stop')

    @pytest.mark.run(order=3)
    @allure.title('hpo_gridsearch_search_ctl_show_t_task')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_show_t_task_step2.txt')
    def test_hpo_gridsearch_search_ctl_show_t_task(self):
        ssh.executor("""search-run -t hpo_gridsearch_search_ctl_show_t_task05202224 ../configs/hpo/gridsearch/search_config.yaml &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_show_t_task_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""srun -p pat_dev -n 1 search-ctl show -t hpo_gridsearch_search_ctl_show_t_task05202224 &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_show_t_task_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'JobStatus.FINISHED', '/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_show_t_task')

    @pytest.mark.run(order=4)
    @allure.title('hpo_gridsearch_search_ctl_export_t_task')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_export_t_task_step4.txt')
    def test_hpo_gridsearch_search_ctl_export_t_task(self):
        ssh.executor("""search-run -t hpo_gridsearch_search_ctl_export_t_task05202224 ../configs/hpo/gridsearch/search_config.yaml &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_export_t_task_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""search-ctl export -t hpo_gridsearch_search_ctl_export_t_task05202224 --tar-path ~/gml_daily/gml/hpo_gridsearch_search_ctl_export_t_task05202224.tar &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_export_t_task_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""cd ~/gml_daily/gml &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_export_t_task_step3.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        Utils.get_result_from_consule(ssh, """setarg(${{EXPORT}},ls | grep *.tar) &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_export_t_task_step4.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'hpo_gridsearch_search_ctl_export_t_task05202224.tar', '/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_export_t_task')

    @pytest.mark.run(order=5)
    @allure.title('hpo_gridsearch_search_ctl_import_t_task')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_import_t_task_step2.txt')
    def test_hpo_gridsearch_search_ctl_import_t_task(self):
        ssh.executor("""cd  ~/gml_daily/gml/demo &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_import_t_task_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        cli = """search-ctl import -t hpo_gridsearch_search_ctl_import_t_task05202224 --tar-path  ~/gml_daily/gml/${{EXPORT}} &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_import_t_task_step2.txt"""
        global_arg = Utils.get_json_value()
        print(global_arg)
        for k,v in global_arg.items():
                if k in cli:
                        cli = cli.replace("${{" + k + "}}",v)
        ssh.executor(cli)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'import hpo_gridsearch_search_ctl_import_t_task05202224 successfully! load from', '/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_import_t_task')

    @pytest.mark.run(order=6)
    @allure.title('hpo_gridsearch_search_ctl_rm_t_task')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_rm_t_task_step6.txt')
    def test_hpo_gridsearch_search_ctl_rm_t_task(self):
        ssh.executor("""search-run -t hpo_gridsearch_search_ctl_rm_t_task05202224 ../configs/hpo/gridsearch/search_config.yaml &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_rm_t_task_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""tmux new -s hpo_gridsearch_search_ctl_rm_t_task""", max_wait=3)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""tmux detach""", max_wait=3)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""tmux send-keys -t hpo_gridsearch_search_ctl_rm_t_task 'source pt1.6.0 mmcv=1.4.6' C-m""", max_wait=3)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""tmux send-keys -t hpo_gridsearch_search_ctl_rm_t_task 'cd ~/gml_daily/gml/demo' C-m""", max_wait=3)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""tmux send-keys -t hpo_gridsearch_search_ctl_rm_t_task 'search-ctl rm -t hpo_gridsearch_search_ctl_rm_t_task05202224' C-m""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(30)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""tmux send-keys -t hpo_gridsearch_search_ctl_rm_t_task 'y' C-m""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(60)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""srun -p pat_dev -n 1 search-ctl show -t hpo_gridsearch_search_ctl_rm_t_task05202224 &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_rm_t_task_step6.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'hpo_gridsearch_search_ctl_rm_t_task05202224 is not exists', '/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_rm_t_task')

    @pytest.mark.run(order=7)
    @allure.title('hpo_gridsearch_search_ctl_show_all_task')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_show_all_task_step1.txt')
    def test_hpo_gridsearch_search_ctl_show_all_task(self):
        ssh.executor("""srun -p pat_dev -n 1 search-ctl show &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_show_all_task_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'All tasks', '/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_show_all_task')
        assert Utils.assert_result_in_logpath(ssh, 'finished', '/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_show_all_task')

    @pytest.mark.run(order=8)
    @allure.title('hpo_gridsearch_search_ctl_show_scalar')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_show_scalar_step3.txt')
    def test_hpo_gridsearch_search_ctl_show_scalar(self):
        ssh.executor("""tmux new -s hpo_gridsearch_search_ctl_show_scalar""", max_wait=3)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""tmux detach""", max_wait=3)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""tmux send-keys -t hpo_gridsearch_search_ctl_show_scalar 'source pt1.6.0 mmcv=1.4.6' C-m""", max_wait=3)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""tmux send-keys -t hpo_gridsearch_search_ctl_show_scalar 'cd ~/gml_daily/gml/demo' C-m""", max_wait=3)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""tmux send-keys -t hpo_gridsearch_search_ctl_show_scalar 'search-run -t hpo_gridsearch_search_ctl_show_scalar05202224 ../configs/hpo/gridsearch/search_config.yaml' C-m""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(1500)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""srun -p pat_dev -n 1 search-ctl show-scalar -t hpo_gridsearch_search_ctl_show_scalar05202224 -rt 1 &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_show_scalar_step3.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'Test Acc', '/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_show_scalar')

    @pytest.mark.run(order=9)
    @allure.title('hpo_gridsearch_search_ctl_resume')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_resume_step8.txt')
    def test_hpo_gridsearch_search_ctl_resume(self):
        ssh.executor("""tmux new -s hpo_gridsearch_search_ctl_resume""", max_wait=3)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""tmux detach""", max_wait=3)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""tmux send-keys -t hpo_gridsearch_search_ctl_resume 'source pt1.6.0 mmcv=1.4.6' C-m""", max_wait=3)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""tmux send-keys -t hpo_gridsearch_search_ctl_resume 'cd ~/gml_daily/gml/demo' C-m""", max_wait=3)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""tmux send-keys -t hpo_gridsearch_search_ctl_resume 'search-run -t hpo_gridsearch_search_ctl_resume05202224 ../configs/hpo/gridsearch/search_config.yaml' C-m""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(150)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""search-ctl stop -t hpo_gridsearch_search_ctl_resume05202224 &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_resume_step3.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""tmux send-keys -t hpo_gridsearch_search_ctl_resume 'search-ctl resume -t hpo_gridsearch_search_ctl_resume05202224' C-m""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(80)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""tmux send-keys -t hpo_gridsearch_search_ctl_resume 'y' C-m""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(1200)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""srun -p pat_dev -n 1 search-ctl show -t hpo_gridsearch_search_ctl_resume05202224 &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_resume_step8.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'JobStatus.FINISHED', '/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_search_ctl_resume')

    @pytest.mark.run(order=10)
    @allure.title('hpo_gridsearch_MOCK_PAVI0_search_run')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_MOCK_PAVI0_search_run_step2.txt')
    def test_hpo_gridsearch_MOCK_PAVI0_search_run(self):
        ssh.executor("""MOCK_PAVI=0 search-run -t hpo_gridsearch_MOCK_PAVI0_search_run05202224 ../configs/hpo/gridsearch/search_config.yaml &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_MOCK_PAVI0_search_run_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""MOCK_PAVI=0 search-ctl show -t hpo_gridsearch_MOCK_PAVI0_search_run05202224 &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_MOCK_PAVI0_search_run_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'JobStatus.FINISHED', '/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_MOCK_PAVI0_search_run')

    @pytest.mark.run(order=11)
    @allure.title('hpo_gridsearch_MOCK_PAVI1_search_run')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_MOCK_PAVI1_search_run_step2.txt')
    def test_hpo_gridsearch_MOCK_PAVI1_search_run(self):
        ssh.executor("""MOCK_PAVI=1 search-run -t hpo_gridsearch_MOCK_PAVI1_search_run05202224 ../configs/hpo/gridsearch/search_config.yaml &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_MOCK_PAVI1_search_run_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""MOCK_PAVI=1 search-ctl show -t hpo_gridsearch_MOCK_PAVI1_search_run05202224 &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_MOCK_PAVI1_search_run_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'JobStatus.FINISHED', '/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_MOCK_PAVI1_search_run')
        assert Utils.assert_result_in_logpath(ssh, 'mock_compare_url', '/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_MOCK_PAVI1_search_run')

    @pytest.mark.run(order=12)
    @allure.title('hpo_gridsearch_MOCK_PAVI2_search_run')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_MOCK_PAVI2_search_run_step2.txt')
    def test_hpo_gridsearch_MOCK_PAVI2_search_run(self):
        ssh.executor("""MOCK_PAVI=2 search-run -t hpo_gridsearch_MOCK_PAVI2_search_run05202224 ../configs/hpo/gridsearch/search_config.yaml &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_MOCK_PAVI2_search_run_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""MOCK_PAVI=2 search-ctl show -t hpo_gridsearch_MOCK_PAVI2_search_run05202224 &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_MOCK_PAVI2_search_run_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'JobStatus.FINISHED', '/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_MOCK_PAVI2_search_run')
        assert Utils.assert_result_in_logpath(ssh, 'mock_compare_url', '/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_MOCK_PAVI2_search_run')

    @pytest.mark.run(order=13)
    @allure.title('hpo_gridsearch_MOCK_PAVI3_search_run')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_MOCK_PAVI3_search_run_step2.txt')
    def test_hpo_gridsearch_MOCK_PAVI3_search_run(self):
        ssh.executor("""MOCK_PAVI=3 search-run -t hpo_gridsearch_MOCK_PAVI3_search_run05202224 ../configs/hpo/gridsearch/search_config.yaml &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_MOCK_PAVI3_search_run_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""MOCK_PAVI=3 search-ctl show -t hpo_gridsearch_MOCK_PAVI3_search_run05202224 &> /mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_MOCK_PAVI3_search_run_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'JobStatus.FINISHED', '/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_MOCK_PAVI3_search_run')
        assert Utils.assert_result_in_logpath(ssh, 'mock_compare_url', '/mnt/lustre/share/gmllog/pytest_log_05202224/hpo_gridsearch_MOCK_PAVI3_search_run')


class Testkd:

    def setup_class(self):
        ssh.executor('cd ~/gml_daily/gml')

    @pytest.mark.run(order=14)
    @allure.title('kd_ab_loss_pretrain_an_epoch')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/kd_ab_loss_pretrain_an_epoch_step1.txt')
    def test_kd_ab_loss_pretrain_an_epoch(self):
        ssh.executor("""GPUS=1 GPUS_PER_NODE=1 bash tools/slurm_train.sh pat_dev fitnet configs/kd/ab_loss/classification/resnet/abloss_res18_cifar10_distillation_8xb16_teacher_res50_backbone_pretrain.py work_dirs/abloss_res18_cifar10_distillation_8xb16_teacher_res50_backbone_pretrain/ --cfg-options runner.max_epochs=1 &> /mnt/lustre/share/gmllog/pytest_log_05202224/kd_ab_loss_pretrain_an_epoch_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'accuracy_top-1', '/mnt/lustre/share/gmllog/pytest_log_05202224/kd_ab_loss_pretrain_an_epoch')
        assert Utils.assert_result_in_logpath(ssh, 'accuracy_top-5', '/mnt/lustre/share/gmllog/pytest_log_05202224/kd_ab_loss_pretrain_an_epoch')

    @pytest.mark.run(order=15)
    @allure.title('kd_ab_loss_train_an_epoch')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/kd_ab_loss_train_an_epoch_step1.txt')
    def test_kd_ab_loss_train_an_epoch(self):
        ssh.executor("""GPUS=1 GPUS_PER_NODE=1 bash tools/slurm_train.sh pat_dev fitnet configs/kd/ab_loss/classification/resnet/abloss_res18_cifar10_distillation_8xb16_teacher_res50_head_train.py work_dirs/abloss_res18_cifar10_distillation_8xb16_teacher_res50_head_train/ --cfg-options runner.max_epochs=1 &> /mnt/lustre/share/gmllog/pytest_log_05202224/kd_ab_loss_train_an_epoch_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'mme - INFO - Now best checkpoint is saved as best_accuracy_top-1_epoch_1.pth.', '/mnt/lustre/share/gmllog/pytest_log_05202224/kd_ab_loss_train_an_epoch')

    @pytest.mark.run(order=16)
    @allure.title('kd_crd_loss_train_a_epoch')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/kd_crd_loss_train_a_epoch_step1.txt')
    def test_kd_crd_loss_train_a_epoch(self):
        ssh.executor("""GPUS=1 GPUS_PER_NODE=1 bash tools/slurm_train.sh pat_dev crd configs/kd/crd_loss/classification/resnet/crdloss_res18_cifar10_distillation_8xb16_teacher_res50_dimout128.py work_dirs/crdloss_res18_cifar10_distillation_8xb16_teacher_res50_dimout128/ --cfg-options runner.max_epochs=1 &> /mnt/lustre/share/gmllog/pytest_log_05202224/kd_crd_loss_train_a_epoch_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'mme - INFO - Now best checkpoint is saved as best_accuracy_top-1_epoch_1.pth.', '/mnt/lustre/share/gmllog/pytest_log_05202224/kd_crd_loss_train_a_epoch')

    @pytest.mark.run(order=17)
    @allure.title('kd_factor_transfer_pretrain_an_epoch')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/kd_factor_transfer_pretrain_an_epoch_step1.txt')
    def test_kd_factor_transfer_pretrain_an_epoch(self):
        ssh.executor("""GPUS=1 GPUS_PER_NODE=1 bash tools/slurm_train.sh pat_dev fitnet configs/kd/factor_transfer/classification/resnet/ftloss_res18_cifar10_distillation_8xb16_teacher_res50_neck_pretrain.py work_dirs/ftloss_res18_cifar10_distillation_8xb16_teacher_res50_neck_pretrain/ --cfg-options runner.max_epochs=1 &> /mnt/lustre/share/gmllog/pytest_log_05202224/kd_factor_transfer_pretrain_an_epoch_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'accuracy_top-1', '/mnt/lustre/share/gmllog/pytest_log_05202224/kd_factor_transfer_pretrain_an_epoch')
        assert Utils.assert_result_in_logpath(ssh, 'accuracy_top-5', '/mnt/lustre/share/gmllog/pytest_log_05202224/kd_factor_transfer_pretrain_an_epoch')

    @pytest.mark.run(order=18)
    @allure.title('kd_factor_transfer_train_an_epoch')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/kd_factor_transfer_train_an_epoch_step1.txt')
    def test_kd_factor_transfer_train_an_epoch(self):
        ssh.executor("""GPUS=1 GPUS_PER_NODE=1 bash tools/slurm_train.sh pat_dev fitnet configs/kd/factor_transfer/classification/resnet/ftloss_res18_cifar10_distillation_8xb16_teacher_res50_neck_train.py work_dirs/ftloss_res18_cifar10_distillation_8xb16_teacher_res50_neck_train/ --cfg-options runner.max_epochs=1 &> /mnt/lustre/share/gmllog/pytest_log_05202224/kd_factor_transfer_train_an_epoch_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'mme - INFO - Now best checkpoint is saved as best_accuracy_top-1_epoch_1.pth.', '/mnt/lustre/share/gmllog/pytest_log_05202224/kd_factor_transfer_train_an_epoch')

    @pytest.mark.run(order=19)
    @allure.title('kd_fitnet_train_a_epoch')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/kd_fitnet_train_a_epoch_step1.txt')
    def test_kd_fitnet_train_a_epoch(self):
        ssh.executor("""GPUS=1 GPUS_PER_NODE=1 bash tools/slurm_train.sh pat_dev fitnet configs/kd/fitnet/classification/fitnet_res18_cifar10_distillation_8xb16_teacher_res50_s4_mimic.py work_dirs/fitnet_res18_cifar10_distillation_8xb16_teacher_res50_s4_mimic/ --cfg-options runner.max_epochs=1 &> /mnt/lustre/share/gmllog/pytest_log_05202224/kd_fitnet_train_a_epoch_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'mme - INFO - Now best checkpoint is saved as best_accuracy_top-1_epoch_1.pth.', '/mnt/lustre/share/gmllog/pytest_log_05202224/kd_fitnet_train_a_epoch')

    @pytest.mark.run(order=20)
    @allure.title('kd_ofd_train_a_epoch')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/kd_ofd_train_a_epoch_step1.txt')
    def test_kd_ofd_train_a_epoch(self):
        ssh.executor("""GPUS=1 GPUS_PER_NODE=1 bash tools/slurm_train.sh pat_dev fitnet configs/kd/ofd/classification/resnet/ofdloss_res18_cifar10_distillation_8xb16_teacher_res50_train.py work_dirs/ofdloss_res18_cifar10_distillation_8xb16_teacher_res50_train --cfg-options runner.max_epochs=1 &> /mnt/lustre/share/gmllog/pytest_log_05202224/kd_ofd_train_a_epoch_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'mme - INFO - Now best checkpoint is saved as best_accuracy_top-1_epoch_1.pth.', '/mnt/lustre/share/gmllog/pytest_log_05202224/kd_ofd_train_a_epoch')

    @pytest.mark.run(order=21)
    @allure.title('kd_rkd_train_a_epoch')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/kd_rkd_train_a_epoch_step1.txt')
    def test_kd_rkd_train_a_epoch(self):
        ssh.executor("""GPUS=1 GPUS_PER_NODE=1 bash tools/slurm_train.sh pat_dev fitnet configs/kd/rkd/classification/resnet/rkdd_rkda_res18_cifar10_distillation_8xb16_teacher_res50_neck_mimic.py work_dirs/rkdd_rkda_res18_cifar10_distillation_8xb16_teacher_res50_neck_mimic --cfg-options runner.max_epochs=1 &> /mnt/lustre/share/gmllog/pytest_log_05202224/kd_rkd_train_a_epoch_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'mme - INFO - Now best checkpoint is saved as best_accuracy_top-1_epoch_1.pth.', '/mnt/lustre/share/gmllog/pytest_log_05202224/kd_rkd_train_a_epoch')


class Testnas:

    def setup_class(self):
        ssh.executor('cd ~/gml_daily/gml')

    @pytest.mark.run(order=22)
    @allure.title('nas_darts_darts_supernet_train')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/nas_darts_darts_supernet_train_step2.txt')
    def test_nas_darts_darts_supernet_train(self):
        ssh.executor("""sed -i "s/max_epochs=50/max_epochs=1/g" ./configs/nas/darts/cifar10_bs16_supernet.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_darts_darts_supernet_train_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""GPUS=4 GPUS_PER_NODE=4 tools/slurm_train.sh pat_dev nas_darts_darts_supernet_train configs/nas/darts/darts_cellbase_cifar10_supernet_1xb64.py work_dirs/darts_supernet_train &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_darts_darts_supernet_train_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(180)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'Search finished', '/mnt/lustre/share/gmllog/pytest_log_05202224/nas_darts_darts_supernet_train')

    @pytest.mark.run(order=23)
    @allure.title('nas_darts_darts_supernet_test')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/nas_darts_darts_supernet_test_step3.txt')
    def test_nas_darts_darts_supernet_test(self):
        ssh.executor("""sed -i "s/max_epoch=600/max_epoch=1/g" configs/nas/darts/cifar10_bs96_subnet.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_darts_darts_supernet_test_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        Utils.get_result_from_consule(ssh, """setarg(${{EXPORT_YAML}},find work_dirs/darts_supernet_train -name "*.yaml") &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_darts_darts_supernet_test_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        cli = """GPUS=4 GPUS_PER_NODE=4 tools/slurm_test.sh pat_dev nas_darts_darts_supernet_test configs/nas/darts/darts_cellbase_cifar10_subnet_1xb96.py work_dirs/darts_supernet_train/latest.pth --work-dir work_dirs/xxx_test --eval accuracy --cfg-options algorithm.mutable_cfg=${{EXPORT_YAML}} &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_darts_darts_supernet_test_step3.txt"""
        global_arg = Utils.get_json_value()
        print(global_arg)
        for k,v in global_arg.items():
                if k in cli:
                        cli = cli.replace("${{" + k + "}}",v)
        ssh.executor(cli)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(180)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'accuracy_top-1', '/mnt/lustre/share/gmllog/pytest_log_05202224/nas_darts_darts_supernet_test')
        assert Utils.assert_result_in_logpath(ssh, 'accuracy_top-5', '/mnt/lustre/share/gmllog/pytest_log_05202224/nas_darts_darts_supernet_test')

    @pytest.mark.run(order=24)
    @allure.title('nas_bignas_bignas_supernet_train')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/nas_bignas_bignas_supernet_train_step4.txt')
    def test_nas_bignas_bignas_supernet_train(self):
        ssh.executor("""sed -i "s/max_epochs=360/max_epochs=1/g" ./configs/nas/bignas/bignas_mobilenetv3_large_supernet_32xb64.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_bignas_bignas_supernet_train_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/samples_per_gpu=64/samples_per_gpu=32/g" ./configs/nas/bignas/bignas_mobilenetv3_large_supernet_32xb64.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_bignas_bignas_supernet_train_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s#/mnt/lustre/share_data/wangshiguang/train_4k.txt#data/gml_unique/imagenet-1k/meta/train.txt#g" ./configs/nas/bignas/bignas_mobilenetv3_large_supernet_32xb64.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_bignas_bignas_supernet_train_step3.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""GPUS=4 GPUS_PER_NODE=4 tools/slurm_train.sh pat_dev nas_bignas_bignas_supernet_train configs/nas/bignas/bignas_mobilenetv3_large_supernet_32xb64.py work_dirs/bignas_supernet_train &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_bignas_bignas_supernet_train_step4.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(180)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'Saving checkpoint at 1 epochs', '/mnt/lustre/share/gmllog/pytest_log_05202224/nas_bignas_bignas_supernet_train')

    @pytest.mark.run(order=25)
    @allure.title('nas_bignas_bignas_supernet_search')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/nas_bignas_bignas_supernet_search_step5.txt')
    def test_nas_bignas_bignas_supernet_search(self):
        ssh.executor("""sed -i "s/candidate_pool_size=256/candidate_pool_size=2/g" ./configs/nas/bignas/bignas_mobilenetv3_large_evolution_search_8xb256.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_bignas_bignas_supernet_search_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/max_epoch=20/max_epoch=1/g" ./configs/nas/bignas/bignas_mobilenetv3_large_evolution_search_8xb256.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_bignas_bignas_supernet_search_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s#/mnt/lustre/share_data/wangshiguang/train_4k.txt#data/gml_unique/imagenet-1k/meta/train.txt#g" ./configs/nas/bignas/bignas_mobilenetv3_large_evolution_search_8xb256.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_bignas_bignas_supernet_search_step3.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s#data_prefix='data/imagenet/#data_prefix='s3://PAT/datasets/project_data/gml_data/gml_unique/imagenet_1k/#g" ./configs/nas/bignas/bignas_mobilenetv3_large_evolution_search_8xb256.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_bignas_bignas_supernet_search_step4.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""GPUS=4 GPUS_PER_NODE=4 tools/slurm_search.sh pat_dev nas_bignas_bignas_supernet_search configs/nas/bignas/bignas_mobilenetv3_large_evolution_search_8xb256.py work_dirs/bignas_supernet_train/latest.pth --work-dir work_dirs/bignas_search &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_bignas_bignas_supernet_search_step5.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(180)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'Search finished', '/mnt/lustre/share/gmllog/pytest_log_05202224/nas_bignas_bignas_supernet_search')

    @pytest.mark.run(order=26)
    @allure.title('nas_bignas_bignas_supernet_test')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/nas_bignas_bignas_supernet_test_step4.txt')
    def test_nas_bignas_bignas_supernet_test(self):
        ssh.executor("""sed -i "s/max_epoch=360/max_epoch=1/g" ./configs/nas/bignas/bignas_mobilenetv3_large_subnet_8xb128_flops600M.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_bignas_bignas_supernet_test_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        Utils.get_result_from_consule(ssh, """setarg(${{EXPORT_YAML}},find ./work_dirs/bignas_search -name "final_subnet_step5*.yaml") &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_bignas_bignas_supernet_test_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        Utils.get_result_from_consule(ssh, """setarg(${{EXPORT_PTH}},find ./work_dirs/bignas_search -name "final_subnet_step5*.pth") &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_bignas_bignas_supernet_test_step3.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        cli = """GPUS=4 GPUS_PER_NODE=4 tools/slurm_test.sh pat_dev nas_bignas_bignas_supernet_test  configs/nas/bignas/bignas_mobilenetv3_large_subnet_16xb128_flops600M.py ${{EXPORT_PTH}} --work-dir work_dirs/xxx_test --eval accuracy --cfg-options algorithm.mutable_cfg=${{EXPORT_YAML}} &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_bignas_bignas_supernet_test_step4.txt"""
        global_arg = Utils.get_json_value()
        print(global_arg)
        for k,v in global_arg.items():
                if k in cli:
                        cli = cli.replace("${{" + k + "}}",v)
        ssh.executor(cli)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(180)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'accuracy_top-1', '/mnt/lustre/share/gmllog/pytest_log_05202224/nas_bignas_bignas_supernet_test')

    @pytest.mark.run(order=27)
    @allure.title('nas_spos_spos_supernet_train')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_supernet_train_step3.txt')
    def test_nas_spos_spos_supernet_train(self):
        ssh.executor("""sed -i "s/max_iters=150000/max_iters=100/g" ./configs/nas/spos/spos_shufflenetv2_supernet_8xb128_in1k.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_supernet_train_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/dict(interval=1000)/dict(interval=100)/g" ./configs/nas/spos/spos_shufflenetv2_supernet_8xb128_in1k.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_supernet_train_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""GPUS=4 GPUS_PER_NODE=4 tools/slurm_train.sh pat_dev nas_spos_spos_supernet_train configs/nas/spos/spos_shufflenetv2_supernet_8xb128_in1k.py work_dirs/spos_supernet &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_supernet_train_step3.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(180)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'Saving checkpoint', '/mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_supernet_train')

    @pytest.mark.run(order=28)
    @allure.title('nas_spos_spos_supernet_search')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_supernet_search_step8.txt')
    def test_nas_spos_spos_supernet_search(self):
        Utils.get_result_from_consule(ssh, """setarg(${{EXPORT_PTH}},find ./ -name "latest.pth") &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_supernet_search_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/candidate_pool_size=50/candidate_pool_size=5/g" ./configs/nas/spos/spos_shufflenetv2_evolution_search_8xb2048_in1k.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_supernet_search_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/candidate_top_k=10/candidate_top_k=2/g" ./configs/nas/spos/spos_shufflenetv2_evolution_search_8xb2048_in1k.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_supernet_search_step3.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/max_epoch=20/max_epoch=2/g" ./configs/nas/spos/spos_shufflenetv2_evolution_search_8xb2048_in1k.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_supernet_search_step4.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/candidate_pool_size=50/candidate_pool_size=5/g" ./configs/nas/spos/spos_shufflenetv2_evolution_search_8xb2048_in1k.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_supernet_search_step5.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/num_mutation=25/num_mutation=2/g" ./configs/nas/spos/spos_shufflenetv2_evolution_search_8xb2048_in1k.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_supernet_search_step6.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/num_crossover=25/num_crossover=3/g" ./configs/nas/spos/spos_shufflenetv2_evolution_search_8xb2048_in1k.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_supernet_search_step7.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""GPUS=4 GPUS_PER_NODE=4 tools/slurm_search.sh pat_dev nas_spos_spos_supernet_search configs/nas/spos/spos_shufflenetv2_evolution_search_8xb2048_in1k.py work_dirs/spos_supernet/latest.pth --work-dir work_dirs/spos_search &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_supernet_search_step8.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(180)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'Search finished', '/mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_supernet_search')

    @pytest.mark.run(order=29)
    @allure.title('nas_spos_spos_subnet_retrain')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_subnet_retrain_step3.txt')
    def test_nas_spos_spos_subnet_retrain(self):
        Utils.get_result_from_consule(ssh, """setarg(${{EXPORT_YAML}},find ./work_dirs/spos_search -name "*.yaml") &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_subnet_retrain_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/max_iters=300000/max_iters=100/g" ./configs/nas/spos/spos_shufflenetv2_subnet_8xb128_in1k.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_subnet_retrain_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        cli = """GPUS=4 GPUS_PER_NODE=4 tools/slurm_train.sh pat_dev nas_spos_spos_subnet_retrain configs/nas/spos/spos_shufflenetv2_subnet_8xb128_in1k.py work_dirs/spos_retrain --cfg-options algorithm.mutable_cfg=${{EXPORT_YAML}} &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_subnet_retrain_step3.txt"""
        global_arg = Utils.get_json_value()
        print(global_arg)
        for k,v in global_arg.items():
                if k in cli:
                        cli = cli.replace("${{" + k + "}}",v)
        ssh.executor(cli)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(180)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'Saving checkpoint', '/mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_subnet_retrain')

    @pytest.mark.run(order=30)
    @allure.title('nas_spos_spos_subnet_test')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_subnet_test_step3.txt')
    def test_nas_spos_spos_subnet_test(self):
        Utils.get_result_from_consule(ssh, """setarg(${{EXPORT_PTH}},find ./work_dirs/spos_retrain -name "latest.pth") &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_subnet_test_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        Utils.get_result_from_consule(ssh, """setarg(${{EXPORT_YAML}},find ./work_dirs/spos_search -name "*.yaml") &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_subnet_test_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        cli = """GPUS=4 GPUS_PER_NODE=4 tools/slurm_test.sh pat_dev nas_spos_spos_subnet_test configs/nas/spos/spos_shufflenetv2_subnet_8xb128_in1k.py ${{EXPORT_PTH}} --work-dir work_dirs/spos_test --eval accuracy --cfg-options algorithm.mutable_cfg=${{EXPORT_YAML}} &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_subnet_test_step3.txt"""
        global_arg = Utils.get_json_value()
        print(global_arg)
        for k,v in global_arg.items():
                if k in cli:
                        cli = cli.replace("${{" + k + "}}",v)
        ssh.executor(cli)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(180)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'accuracy_top-1', '/mnt/lustre/share/gmllog/pytest_log_05202224/nas_spos_spos_subnet_test')

    @pytest.mark.run(order=31)
    @allure.title('nas_zennas_zennas_supernet_search')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/nas_zennas_zennas_supernet_search_step6.txt')
    def test_nas_zennas_zennas_supernet_search(self):
        ssh.executor("""sed -i "s/num_crossover=128/num_crossover=3/g" ./configs/nas/zennas/mobilenetv3_zenscore_evolution_search_8xb256.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_zennas_zennas_supernet_search_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/candidate_pool_size=256/candidate_pool_size=5/g" ./configs/nas/zennas/mobilenetv3_zenscore_evolution_search_8xb256.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_zennas_zennas_supernet_search_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/candidate_top_k=256/candidate_top_k=2/g" ./configs/nas/zennas/mobilenetv3_zenscore_evolution_search_8xb256.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_zennas_zennas_supernet_search_step3.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/max_epoch=20/max_epoch=2/g" ./configs/nas/zennas/mobilenetv3_zenscore_evolution_search_8xb256.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_zennas_zennas_supernet_search_step4.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/num_mutation=128/num_mutation=2/g" ./configs/nas/zennas/mobilenetv3_zenscore_evolution_search_8xb256.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_zennas_zennas_supernet_search_step5.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""GPUS=4 GPUS_PER_NODE=4 tools/slurm_search.sh pat_dev nas_zennas_zennas_supernet_search configs/nas/zennas/mobilenetv3_zenscore_evolution_search_8xb256.py data/gml_checkpoint/0310_bignas_latest.pth --work-dir work_dirs/zennas_supernet_search &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_zennas_zennas_supernet_search_step6.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(180)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'Search finished', '/mnt/lustre/share/gmllog/pytest_log_05202224/nas_zennas_zennas_supernet_search')

    @pytest.mark.run(order=32)
    @allure.title('nas_zennas_zennas_supernet_retrain')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/nas_zennas_zennas_supernet_retrain_step3.txt')
    def test_nas_zennas_zennas_supernet_retrain(self):
        ssh.executor("""sed -i "s#efficientnet-b3_8xb32_in1k_timm_84_01_v3.pth#~/gml_daily/gml/data/gml_checkpoint/efficientnet-b3_8xb32_in1k_timm_84_01_v3.pth#g" configs/nas/zennas/EXP_3_E3tozennet0.1_distillation_8xb64_teacher_mimic_ns_connnector.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_zennas_zennas_supernet_retrain_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/max_epochs=480/max_epochs=1/g" configs/nas/zennas/EXP_3_E3tozennet0.1_distillation_8xb64_teacher_mimic_ns_connnector.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_zennas_zennas_supernet_retrain_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""GPUS=4 GPUS_PER_NODE=4 tools/slurm_train.sh pat_dev nas_zennas_zennas_supernet_retrain configs/nas/zennas/EXP_3_E3tozennet0.1_distillation_8xb64_teacher_mimic_ns_connnector.py work_dirs/nas_zennas_zennas_supernet_retrain &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_zennas_zennas_supernet_retrain_step3.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(180)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'Saving checkpoint', '/mnt/lustre/share/gmllog/pytest_log_05202224/nas_zennas_zennas_supernet_retrain')

    @pytest.mark.run(order=33)
    @allure.title('nas_cream_cream_supernet_train')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/nas_cream_cream_supernet_train_step4.txt')
    def test_nas_cream_cream_supernet_train(self):
        ssh.executor("""sed -i "s/max_epochs=120/max_epochs=2/g" ./configs/nas/cream/cream_mobilenetv3_supernet_8xb128_max500M.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_cream_cream_supernet_train_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/meta_sta_epoch=20/meta_sta_epoch=-1/g" ./configs/nas/cream/cream_mobilenetv3_supernet_8xb128_max500M.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_cream_cream_supernet_train_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/samples_per_gpu=128/samples_per_gpu=64/g" ./configs/_base_/datasets/mmcls/imagenet_bs128_cream_224.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_cream_cream_supernet_train_step3.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""GPUS=4 GPUS_PER_NODE=4 tools/slurm_train.sh pat_dev nas_cream_cream_supernet_train configs/nas/cream/cream_mobilenetv3_supernet_8xb128_max500M.py work_dirs/cream_supernet &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_cream_cream_supernet_train_step4.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(180)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'Saving checkpoint', '/mnt/lustre/share/gmllog/pytest_log_05202224/nas_cream_cream_supernet_train')

    @pytest.mark.run(order=34)
    @allure.title('nas_cream_cream_subnet_retrain')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/nas_cream_cream_subnet_retrain_step4.txt')
    def test_nas_cream_cream_subnet_retrain(self):
        Utils.get_result_from_consule(ssh, """setarg(${{EXPORT_YAML}},find ./work_dirs/cream_supernet -name "*.yaml") &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_cream_cream_subnet_retrain_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/max_epochs=530/max_epochs=2/g" ./configs/nas/cream/cream_mobilenetv3_subnet_16xb128_max500M.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_cream_cream_subnet_retrain_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/samples_per_gpu=128/samples_per_gpu=64/g" ./configs/_base_/datasets/mmcls/imagenet_bs128_cream_224.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_cream_cream_subnet_retrain_step3.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        cli = """GPUS=4 GPUS_PER_NODE=4 tools/slurm_train.sh pat_dev nas_cream_cream_subnet_retrain configs/nas/cream/cream_mobilenetv3_subnet_16xb128_max500M.py work_dirs/cream_retrain --cfg-options algorithm.mutable_cfg=${{EXPORT_YAML}} &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_cream_cream_subnet_retrain_step4.txt"""
        global_arg = Utils.get_json_value()
        print(global_arg)
        for k,v in global_arg.items():
                if k in cli:
                        cli = cli.replace("${{" + k + "}}",v)
        ssh.executor(cli)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(180)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'Saving checkpoint', '/mnt/lustre/share/gmllog/pytest_log_05202224/nas_cream_cream_subnet_retrain')

    @pytest.mark.run(order=35)
    @allure.title('nas_cream_cream_subnet_test')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/nas_cream_cream_subnet_test_step3.txt')
    def test_nas_cream_cream_subnet_test(self):
        Utils.get_result_from_consule(ssh, """setarg(${{EXPORT_PTH}},find ./work_dirs/cream_retrain -name "latest.pth") &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_cream_cream_subnet_test_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        Utils.get_result_from_consule(ssh, """setarg(${{EXPORT_YAML}},find ./work_dirs/cream_supernet -name "*.yaml") &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_cream_cream_subnet_test_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        cli = """GPUS=4 GPUS_PER_NODE=4 tools/slurm_test.sh pat_dev nas_cream_cream_subnet_test configs/nas/cream/cream_mobilenetv3_subnet_16xb128_max500M.py ${{EXPORT_PTH}} --eval accuracy --cfg-options algorithm.mutable_cfg=${{EXPORT_YAML}} &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_cream_cream_subnet_test_step3.txt"""
        global_arg = Utils.get_json_value()
        print(global_arg)
        for k,v in global_arg.items():
                if k in cli:
                        cli = cli.replace("${{" + k + "}}",v)
        ssh.executor(cli)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(180)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'accuracy_top-1', '/mnt/lustre/share/gmllog/pytest_log_05202224/nas_cream_cream_subnet_test')

    @pytest.mark.run(order=36)
    @allure.title('nas_nsganet_nsganet_supernet_train')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/nas_nsganet_nsganet_supernet_train_step3.txt')
    def test_nas_nsganet_nsganet_supernet_train(self):
        ssh.executor("""sed -i "s/max_epochs=1/max_epochs=2/g" ./configs/nas/nsganet/imagenet/nsganet_supernet_8xb256.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_nsganet_nsganet_supernet_train_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        Utils.get_result_from_consule(ssh, """setarg(${{SUPERNET_FILE}},find ./configs/nas/nsganet/imagenet/ -name "nsganet_supernet_*.py") &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_nsganet_nsganet_supernet_train_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        cli = """GPUS=4 GPUS_PER_NODE=4 tools/slurm_train.sh pat_dev nas_nsganet_nsganet_supernet_train ${{SUPERNET_FILE}} work_dirs/nsganet_supernet &> /mnt/lustre/share/gmllog/pytest_log_05202224/nas_nsganet_nsganet_supernet_train_step3.txt"""
        global_arg = Utils.get_json_value()
        print(global_arg)
        for k,v in global_arg.items():
                if k in cli:
                        cli = cli.replace("${{" + k + "}}",v)
        ssh.executor(cli)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        time.sleep(180)
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'Saving checkpoint', '/mnt/lustre/share/gmllog/pytest_log_05202224/nas_nsganet_nsganet_supernet_train')


class Testpruning:

    def setup_class(self):
        ssh.executor('cd ~/gml_daily/gml')

    @pytest.mark.run(order=37)
    @allure.title('pruning_dmcp_dmcp_mbv2_train')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/pruning_dmcp_dmcp_mbv2_train_step6.txt')
    def test_pruning_dmcp_dmcp_mbv2_train(self):
        ssh.executor("""sed -i "s/max_epochs=60/max_epochs=1/g" ./configs/pruning/dmcp/dmcp_mobilenetv2_imagenet_8xb256_f150.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/pruning_dmcp_dmcp_mbv2_train_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/target_flops=150/target_flops=315/g" ./configs/pruning/dmcp/dmcp_mobilenetv2_imagenet_8xb256_f150.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/pruning_dmcp_dmcp_mbv2_train_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/distill_iter=2000/distill_iter=10/g" ./configs/pruning/dmcp/dmcp_mobilenetv2_imagenet_8xb256_f150.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/pruning_dmcp_dmcp_mbv2_train_step3.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/arch_start_train=None/arch_start_train=2000/g" ./configs/pruning/dmcp/dmcp_mobilenetv2_imagenet_8xb256_f150.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/pruning_dmcp_dmcp_mbv2_train_step4.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s/samples_per_gpu=256/samples_per_gpu=128/g" ./configs/_base_/datasets/mmcls/imagenet_bs256_autoslim.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/pruning_dmcp_dmcp_mbv2_train_step5.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""GPUS=1 GPUS_PER_NODE=1 tools/slurm_train.sh pat_dev pruning_dmcp_dmcp_mbv2_train configs/pruning/dmcp/dmcp_mobilenetv2_imagenet_8xb256_f150.py work_dirs/dmcp_mbv2_train &> /mnt/lustre/share/gmllog/pytest_log_05202224/pruning_dmcp_dmcp_mbv2_train_step6.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'Saving checkpoint at 1 epochs', '/mnt/lustre/share/gmllog/pytest_log_05202224/pruning_dmcp_dmcp_mbv2_train')

    @pytest.mark.run(order=38)
    @allure.title('pruning_dmcp_dmcp_mbv2_retrain')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/pruning_dmcp_dmcp_mbv2_retrain_step3.txt')
    def test_pruning_dmcp_dmcp_mbv2_retrain(self):
        ssh.executor("""sed -i "s/max_epochs=60/max_epochs=1/g" ./configs/pruning/dmcp/dmcp_mobilenetv2_imagenet_8xb256_retrain.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/pruning_dmcp_dmcp_mbv2_retrain_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""sed -i "s#/DMCP_WORKDIR/model_sample/subnet.npy#work_dirs/dmcp_mbv2_train/model_sample/subnet_1.npy#g" ./configs/pruning/dmcp/dmcp_mobilenetv2_imagenet_8xb256_retrain.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/pruning_dmcp_dmcp_mbv2_retrain_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""GPUS=1 GPUS_PER_NODE=1 tools/slurm_train.sh pat_dev pruning_dmcp_dmcp_mbv2_retrain configs/pruning/dmcp/dmcp_mobilenetv2_imagenet_8xb256_retrain.py work_dirs/dmcp_mbv2_retrain &> /mnt/lustre/share/gmllog/pytest_log_05202224/pruning_dmcp_dmcp_mbv2_retrain_step3.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'Retrain finished', '/mnt/lustre/share/gmllog/pytest_log_05202224/pruning_dmcp_dmcp_mbv2_retrain')

    @pytest.mark.run(order=39)
    @allure.title('pruning_dcff_dcff_resnet50')
    @allure.description('这个case结果log文件都在集群10.5.36.31这个文件中：/mnt/lustre/share/gmllog/pytest_log_05202224/pruning_dcff_dcff_resnet50_step2.txt')
    def test_pruning_dcff_dcff_resnet50(self):
        ssh.executor("""sed -i "s/max_epochs=120/max_epochs=1/g" ./configs/pruning/dcff/classification/dcff_resnet50_imagenet_8xb32.py &> /mnt/lustre/share/gmllog/pytest_log_05202224/pruning_dcff_dcff_resnet50_step1.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        ssh.executor("""GPUS=1 GPUS_PER_NODE=1 tools/slurm_train.sh pat_dev pruning_dcff_dcff_resnet50 configs/pruning/dcff/classification/dcff_resnet50_imagenet_8xb32.py work_dirs/dcff_resnet50 &> /mnt/lustre/share/gmllog/pytest_log_05202224/pruning_dcff_dcff_resnet50_step2.txt""")
        print('现在的准确时间是：{}'.format(time.strftime('%m%d%H%M', time.localtime())))
        assert Utils.assert_result_in_logpath(ssh, 'Train finished and save checkpoint at 1 epochs', '/mnt/lustre/share/gmllog/pytest_log_05202224/pruning_dcff_dcff_resnet50')